apiVersion: apps/v1
kind: Deployment

metadata:
  name: test-local-reg-website-deployment

spec:
  selector:
    matchLabels:
      app: test-local-reg-website-deployment

  template:
    metadata:
      labels:
        app: test-local-reg-website-deployment

    spec:
      containers:
      - name: website
        image: test-local-reg-website-deployment:latest
        imagePullPolicy: IfNotPresent

  replicas: 1