apiVersion: v1
kind: Service

metadata:
  name: 42069-test-service
  labels:
    app: 42069-test-service

spec:
  type: NodePort
  selector:
    app: 42069-test-service
  ports:
    - port: 42069
      targetPort: 42069
      protocol: TCP