apiVersion: v1
kind: Service

metadata:
  name: test-local-reg-website-service
  labels:
    app: test-local-reg-website-deployment

spec:
  type: NodePort
  selector:
    app: test-local-reg-website-deployment
  ports:
    - port: 42069
      targetPort: 42069
      protocol: TCP