apiVersion: apps/v1
kind: Deployment

metadata:
  name: 42069-test-deploy

spec:
  selector:
    matchLabels:
      app: 42069-test-deploy

  template:
    metadata:
      labels:
        app: 42069-test-deploy

    spec:
      containers:
      - name: 42069-test-deploy
        image: localhost:5000/42069-test-deploy
        imagePullPolicy: IfNotPresent

  replicas: 1